Update module.yaml
Signed-off-by: stlef14 <stlef14@users.noreply.github.com>

diff --git a/scanners/boostsecurityio/trivy-sbom/module.yaml b/scanners/boostsecurityio/trivy-sbom/module.yaml
--- a/scanners/boostsecurityio/trivy-sbom/module.yaml
+++ b/scanners/boostsecurityio/trivy-sbom/module.yaml
@@ -9,6 +9,15 @@ scan_types:
 config:
   support_diff_scan: false
 
+setup:
+  - name: Verify dotnet installed
+    run: |
+      if ! command -v dotnet &> /dev/null
+      then
+        echo "dotnet is not installed, it is required to run this scanner."
+        exit 1
+      fi
+
 steps:
   - scan:
       command:
