Update module.yaml
Signed-off-by: stlef14 <stlef14@users.noreply.github.com>

diff --git a/scanners/boostsecurityio/trivy-sbom/module.yaml b/scanners/boostsecurityio/trivy-sbom/module.yaml
--- a/scanners/boostsecurityio/trivy-sbom/module.yaml
+++ b/scanners/boostsecurityio/trivy-sbom/module.yaml
@@ -12,9 +12,11 @@ config:
 setup:
   - name: Verify dotnet installed
     run: |
+      #!/usr/bin/env bash
+      set -e
       if ! command -v dotnet &> /dev/null
       then
-        echo "dotnet is not installed, it is required to run this scanner."
+        echo "dotnet is not installed, the scanner cannot run."
         exit 1
       fi
 
